### ISSUE TITLE
Documentation of maxSafeInteger and minSafeInteger is unclear

### ISSUE THREAD

**Issue by malaire** [elm-community/basics-extra#15]
In documentation of `maxSafeInteger` following is unclear:
> maxSafeInteger + 1 --> maxSafeInteger + 2

Meaning of `-->` here is unclear. It's trivial to check that `maxSafeInteger + 1` can be represented exactly and doesn't become `maxSafeInteger + 2`.
```
$ elm repl
> import Basics.Extra exposing (..)
> maxSafeInteger
9007199254740991 : number
> maxSafeInteger + 1
9007199254740992 : number
```

However in the other way around `maxSafeInteger + 2` does become `maxSafeInteger + 1`:
```
...
> maxSafeInteger + 2
9007199254740992 : number
```

Similarly in documentation of `minSafeInteger` following is unclear:
>  minSafeInteger - 1 --> minSafeInteger - 2

**Comment by pzp1997** [comment]
I can see why this might be confusing, let me try to explain. 

- The arrow notation is used to assert equality for the purposes of [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples). 
- In terms of the choice of value, it is the same as JavaScript's [Number.MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER). 
- Although `maxSafeInteger + 1` can be represented exactly, it is unsafe in the sense that if I have the value `9007199254740992` it is impossible to know whether it is `maxSafeInteger + 1` or `maxSafeInteger + 2`. 

Does my explanation clear things up? If not, please suggest how we could update the docs to make things clearer.

**Comment by malaire** [comment]
Ah yes, for some reason I completely forgot that `-->` comes from elm-verify-examples, even though I use that myself everyday.
