### ISSUE TITLE
=> should have higher precedence

### ISSUE THREAD

**Issue by ccapndave** [elm-community/basics-extra#5]
The precedence of the `=>` operator is a bit low; for example its not possible to write:

```elm
JE.object
    [ ("initial" => state.initial |> (Maybe.map JE.int >> Maybe.withDefault JE.null)
    ]
```

... but in fact with the current precedence its necessary to enclose the right hand side in brackets:

```elm
JE.object
    [ ("initial" => (state.initial |> (Maybe.map JE.int >> Maybe.withDefault JE.null))
    ]
```

Experimentation has shown that 8 is a good precedence level.

**Comment by jvoigtlaender** [comment]
I finally had an excuse to make a major version release of the package (due to another change), so the precedence fix is included in that, version 3.0.0.
