### ISSUE TITLE
isSafeInteger broken

### ISSUE THREAD

**Issue by pdavidow** [elm-community/basics-extra#7]
`isSafeInteger 5 == False`
`maxSafeInteger == -1`

but yet
```
> (2^53 - 1)
9007199254740991 : number
```

(running on Windows10 64bit)

**Comment by jvoigtlaender** [comment]
This functionality was added in #4 by @zwilias, maybe he can comment?

**Comment by zwilias** [comment]
Urgh. Seems like Haskell on 32bit platform clips those numbers to 32bit integers. On 64bit platforms, this gives the expected results. Might have to replace those constants by their formulas.

**Comment by zwilias** [comment]
And yes, pdavidow is on 64bit windows, but the elm binaries were likely compiled on/for 32bit architecture. For reference, this does give a correct result on Ellie.
